/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AirflowMissingInfoDialog.java
 *
 * Created on May 10, 2013, 1:56:43 PM
 */
package querygenerator;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JFileChooser;
import json.airflow.Flow;
import json.airflow.ReturnAir;
import json.airflow.SupplyAir;
import json.airflow.Wall;
import json.airflow.Zone;
import net.sf.json.JSONObject;
import org.jdesktop.application.Action;
import utility.FileOperator;
import utility.parser.AirflowMissingInfo;
import utility.parser.AirflowQueriedInfo;

/**
 *
 * @author Nan Yu
 */
public class AirflowMissingInfoDialog extends javax.swing.JDialog {

    /** Creates new form AirflowMissingInfoDialog */
    public AirflowMissingInfoDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        jPanel1.setVisible(true);
        jScrollPane1.setVisible(false);
        jPanel4.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(querygenerator.QueryGeneratorApp.class).getContext().getResourceMap(AirflowMissingInfoDialog.class);
        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jTextArea1.setBackground(resourceMap.getColor("jTextArea1.background")); // NOI18N
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText(resourceMap.getString("jTextArea1.text")); // NOI18N
        jTextArea1.setName("jTextArea1"); // NOI18N

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jTextField1.setText(resourceMap.getString("jTextField1.text")); // NOI18N
        jTextField1.setName("jTextField1"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(querygenerator.QueryGeneratorApp.class).getContext().getActionMap(AirflowMissingInfoDialog.class, this);
        jButton1.setAction(actionMap.get("selectFinalOutputFolder")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        jButton2.setAction(actionMap.get("addMissingInfo")); // NOI18N
        jButton2.setFont(resourceMap.getFont("jButton2.font")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextArea1, 0, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(jButton2)))
                        .addGap(44, 44, 44))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jPanel2.setName("jPanel2"); // NOI18N

        jLabel3.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setFont(resourceMap.getFont("jLabel4.font")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jPanel3.setName("jPanel3"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jTextField2.setText(resourceMap.getString("jTextField2.text")); // NOI18N
        jTextField2.setName("jTextField2"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jTextField3.setText(resourceMap.getString("jTextField3.text")); // NOI18N
        jTextField3.setName("jTextField3"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel6)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel7.setFont(resourceMap.getFont("jLabel7.font")); // NOI18N
        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setFont(resourceMap.getFont("jLabel8.font")); // NOI18N
        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        jButton3.setAction(actionMap.get("finalGenerate")); // NOI18N
        jButton3.setFont(resourceMap.getFont("jButton3.font")); // NOI18N
        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(38, 38, 38))
        );

        jScrollPane1.setViewportView(jPanel2);

        jPanel4.setName("jPanel4"); // NOI18N

        jLabel9.setFont(resourceMap.getFont("jLabel9.font")); // NOI18N
        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        jTextArea2.setBackground(resourceMap.getColor("jTextArea2.background")); // NOI18N
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText(resourceMap.getString("jTextArea2.text")); // NOI18N
        jTextArea2.setName("jTextArea2"); // NOI18N

        jLabel10.setFont(resourceMap.getFont("jLabel10.font")); // NOI18N
        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        jButton4.setAction(actionMap.get("closeDialog")); // NOI18N
        jButton4.setFont(resourceMap.getFont("jButton4.font")); // NOI18N
        jButton4.setText(resourceMap.getString("jButton4.text")); // NOI18N
        jButton4.setName("jButton4"); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(210, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(140, 140, 140))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jTextArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AirflowMissingInfoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AirflowMissingInfoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AirflowMissingInfoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AirflowMissingInfoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                AirflowMissingInfoDialog dialog = new AirflowMissingInfoDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    @Action
    public void selectFinalOutputFolder() {
        JFileChooser targetWorkspaceChooser = new JFileChooser();
        targetWorkspaceChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int n = targetWorkspaceChooser.showOpenDialog(null);
        String filename = targetWorkspaceChooser.getSelectedFile().toString();
        if (n == JFileChooser.APPROVE_OPTION) {
            jTextField1.setText(filename);
        }
    }

    @Action
    public void addMissingInfo() {
        
        //Air Handling System
        jTextField2.setText(airflowMissingInfo.getAhsList().get(0).getName());
        jTextField3.setText(airflowMissingInfo.getAhsList().get(0).getOutdoorAirPercent().toString());
        
        //Zones
        Map<String, Zone> zones = airflowMissingInfo.getZones();
        List<javax.swing.JPanel> zonePanels = new ArrayList<javax.swing.JPanel>();
        for(String zoneName : zones.keySet()){
            zonePanels.add(this.addZonePanel(zones.get(zoneName)));
        }
        
        //Walls
        Map<String, Wall> walls = airflowMissingInfo.getWalls();
        List<javax.swing.JPanel> wallPanels = new ArrayList<javax.swing.JPanel>();
        for(String wallName : walls.keySet()){
            wallPanels.add(this.addWallPanel(walls.get(wallName)));
        }
        this.setPanel2(zonePanels, wallPanels);
        
        jPanel1.setVisible(false);
        jScrollPane1.setVisible(true);
        jPanel4.setVisible(false);
    }
    
    private javax.swing.JPanel addZonePanel(Zone zone){
        
        javax.swing.JPanel jPanel = new javax.swing.JPanel();
        jPanel.setName("jPanel" + nextPanelNum); // NOI18N
        nextPanelNum ++;
        
        javax.swing.JLabel jLabelZoneName = new javax.swing.JLabel();
        jLabelZoneName.setText(zone.getName()); // NOI18N
        jLabelZoneName.setName("jLabel" + nextLabelNum); // NOI18N
        nextLabelNum ++;
        
        javax.swing.JLabel jLabelSupAirFlowValue = new javax.swing.JLabel();
        jLabelSupAirFlowValue.setText("value of supply airflow"); // NOI18N
        jLabelSupAirFlowValue.setName("jLabel" + nextLabelNum); // NOI18N
        nextLabelNum ++;
        
        javax.swing.JTextField jTextFieldSupAirFlowValue = new javax.swing.JTextField();
        jTextFieldSupAirFlowValue.setText(zone.getSupplyAir().get(0).getFlow().getValue().toString()); // NOI18N
        jTextFieldSupAirFlowValue.setName("jTextField" + nextTextFieldNum); // NOI18N
        nextTextFieldNum ++;
        
        javax.swing.JLabel jLabelSupAirFlowUnits = new javax.swing.JLabel();
        jLabelSupAirFlowUnits.setText("units"); // NOI18N
        jLabelSupAirFlowUnits.setName("jLabel" + nextLabelNum); // NOI18N
        nextLabelNum ++;
        
        javax.swing.JTextField jTextFieldSupAirFlowUnits = new javax.swing.JTextField();
        jTextFieldSupAirFlowUnits.setText(zone.getSupplyAir().get(0).getFlow().getUnits()); // NOI18N
        jTextFieldSupAirFlowUnits.setName("jTextField" + nextTextFieldNum); // NOI18N
        nextTextFieldNum ++;
        
        javax.swing.JLabel jLabelRetAirFlowValue = new javax.swing.JLabel();
        jLabelRetAirFlowValue.setText("value of return airflow"); // NOI18N
        jLabelRetAirFlowValue.setName("jLabel" + nextLabelNum); // NOI18N
        nextLabelNum ++;
        
        javax.swing.JTextField jTextFieldRetAirFlowValue = new javax.swing.JTextField();
        jTextFieldRetAirFlowValue.setText(zone.getReturnAir().get(0).getFlow().getValue().toString()); // NOI18N
        jTextFieldRetAirFlowValue.setName("jTextField" + nextTextFieldNum); // NOI18N
        nextTextFieldNum ++;
        
        javax.swing.JLabel jLabelRetAirFlowUnits = new javax.swing.JLabel();
        jLabelRetAirFlowUnits.setText("units"); // NOI18N
        jLabelRetAirFlowUnits.setName("jLabel" + nextLabelNum); // NOI18N
        nextLabelNum ++;
        
        javax.swing.JTextField jTextFieldRetAirFlowUnits = new javax.swing.JTextField();
        jTextFieldRetAirFlowUnits.setText(zone.getReturnAir().get(0).getFlow().getUnits()); // NOI18N
        jTextFieldRetAirFlowUnits.setName("jTextField" + nextTextFieldNum); // NOI18N
        nextTextFieldNum ++;
        
        List<javax.swing.JTextField> textFieldList = new ArrayList<javax.swing.JTextField>();
        textFieldList.add(jTextFieldSupAirFlowValue);
        textFieldList.add(jTextFieldSupAirFlowUnits);
        textFieldList.add(jTextFieldRetAirFlowValue);
        textFieldList.add(jTextFieldRetAirFlowUnits);
        this.zonePanelMap.put(zone.getName(), textFieldList);
        
        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelZoneName)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(jLabelSupAirFlowValue)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldSupAirFlowValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(jLabelRetAirFlowValue)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldRetAirFlowValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(jLabelRetAirFlowUnits)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldRetAirFlowUnits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(jLabelSupAirFlowUnits)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldSupAirFlowUnits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addComponent(jLabelZoneName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSupAirFlowValue)
                    .addComponent(jTextFieldSupAirFlowValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSupAirFlowUnits)
                    .addComponent(jTextFieldSupAirFlowUnits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRetAirFlowValue)
                    .addComponent(jTextFieldRetAirFlowValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRetAirFlowUnits)
                    .addComponent(jTextFieldRetAirFlowUnits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        return jPanel;
    }
    
    private javax.swing.JPanel addWallPanel(Wall wall){
        javax.swing.JPanel jPanel = new javax.swing.JPanel();
        jPanel.setName("jPanel" + nextPanelNum); // NOI18N
        nextPanelNum ++;
        
        javax.swing.JLabel jLabel = new javax.swing.JLabel();
        jLabel.setText("azimuth of "); // NOI18N
        jLabel.setName("jLabel" + nextLabelNum); // NOI18N
        nextLabelNum ++;
        
        javax.swing.JLabel jLabelWallName = new javax.swing.JLabel();
        jLabelWallName.setText(wall.getName()); // NOI18N
        jLabelWallName.setName("jLabel" + nextLabelNum); // NOI18N
        nextLabelNum ++;
        
        javax.swing.JTextField jTextFieldAzimuth = new javax.swing.JTextField();
        jTextFieldAzimuth.setText(wall.getAzimuth().toString()); // NOI18N
        jTextFieldAzimuth.setName("jTextField" + nextTextFieldNum); // NOI18N
        nextTextFieldNum ++;
        
        this.wallPanelMap.put(wall.getName(), jTextFieldAzimuth);
        
        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addComponent(jLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelWallName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldAzimuth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel)
                .addComponent(jLabelWallName)
                .addComponent(jTextFieldAzimuth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        return jPanel;
    }

    private void setPanel2(List<javax.swing.JPanel> zonePanels, List<javax.swing.JPanel> wallPanels){
        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        javax.swing.GroupLayout.ParallelGroup parrellelGroup = jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING);
        javax.swing.GroupLayout.SequentialGroup sequentialGroup = jPanel2Layout.createSequentialGroup();
        sequentialGroup.addContainerGap();
        
        javax.swing.GroupLayout.ParallelGroup subParrellelGroup = jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING);
        subParrellelGroup.addComponent(jLabel8);
        subParrellelGroup.addComponent(jLabel3);
        subParrellelGroup.addComponent(jLabel4);
        subParrellelGroup.addComponent(jLabel7);
        subParrellelGroup.addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE);
        
        javax.swing.GroupLayout.ParallelGroup zonesParallelGroup = jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING);
        for(javax.swing.JPanel zonePanel : zonePanels){
            zonesParallelGroup.addComponent(zonePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE);
        }
        javax.swing.GroupLayout.SequentialGroup zonesSequentialGroup = jPanel2Layout.createSequentialGroup();
        zonesSequentialGroup.addGap(10, 10, 10);
        zonesSequentialGroup.addGroup(zonesParallelGroup);
        
        subParrellelGroup.addGroup(zonesSequentialGroup);
        
        javax.swing.GroupLayout.ParallelGroup wallsParallelGroup = jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING);
        for(javax.swing.JPanel wallPanel : wallPanels){
            wallsParallelGroup.addComponent(wallPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE);
        }
        javax.swing.GroupLayout.SequentialGroup wallsSequentialGroup = jPanel2Layout.createSequentialGroup();
        wallsSequentialGroup.addGap(10, 10, 10);
        wallsSequentialGroup.addGroup(wallsParallelGroup);
        
        subParrellelGroup.addGroup(wallsSequentialGroup);
        subParrellelGroup.addComponent(jButton3);
        
        sequentialGroup.addGroup(subParrellelGroup);
        sequentialGroup.addContainerGap(56, Short.MAX_VALUE);
        
        parrellelGroup.addGroup(sequentialGroup);
        
        jPanel2Layout.setHorizontalGroup(parrellelGroup);
        
        javax.swing.GroupLayout.ParallelGroup verticalParallelGroup = jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING);
        javax.swing.GroupLayout.SequentialGroup verticalSequentialGroup = jPanel2Layout.createSequentialGroup();
        verticalSequentialGroup.addContainerGap();
        verticalSequentialGroup.addComponent(jLabel3);
        verticalSequentialGroup.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED);
        verticalSequentialGroup.addComponent(jLabel4);
        verticalSequentialGroup.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED);
        verticalSequentialGroup.addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE);
        verticalSequentialGroup.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED);
        verticalSequentialGroup.addComponent(jLabel7);
        verticalSequentialGroup.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED);
        for(javax.swing.JPanel zonePanel : zonePanels){
            verticalSequentialGroup.addComponent(zonePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE);
            verticalSequentialGroup.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED);
        }
        verticalSequentialGroup.addComponent(jLabel8);
        verticalSequentialGroup.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED);
        for(javax.swing.JPanel wallPanel : wallPanels){
            verticalSequentialGroup.addComponent(wallPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE);
            verticalSequentialGroup.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED);
        }
        verticalSequentialGroup.addComponent(jButton3);
        verticalSequentialGroup.addGap(20, 20, 20);
        
        verticalParallelGroup.addGroup(verticalSequentialGroup);
        jPanel2Layout.setVerticalGroup(verticalParallelGroup);
        
        jScrollPane1.setViewportView(jPanel2);
    }
    
    @Action
    public void finalGenerate() {
        
        this.getUpdateMissingInfo();
        this.combineFinalResult();
        jLabel10.setText(jTextField1.getText());
        
        jPanel1.setVisible(false);
        jScrollPane1.setVisible(false);
        jPanel4.setVisible(true);
    }
    
    private void getUpdateMissingInfo(){
        //reset ahsList in order to update data from user input
        String ahsName = jTextField2.getText();
        this.airflowMissingInfo.getAhsList().get(0).setName(ahsName);
        this.airflowMissingInfo.getAhsList().get(0).setOutdoorAirPercent(Double.valueOf(jTextField3.getText()));
        
        //reset zones in order to update data from user input
        for(String zoneName : this.airflowMissingInfo.getZones().keySet()){
            Zone zone = this.airflowMissingInfo.getZones().get(zoneName);
            SupplyAir supplyAir = zone.getSupplyAir().get(0);
            supplyAir.setSystem(ahsName);
            Flow supplyFlow = supplyAir.getFlow();
            if(zonePanelMap.get(zoneName).get(0).getText() == null || zonePanelMap.get(zoneName).get(0).getText().length() == 0){
             supplyFlow.setValue(0.0);   
            }
            else{
                supplyFlow.setValue(Double.valueOf(zonePanelMap.get(zoneName).get(0).getText()));
            }
            supplyFlow.setUnits(zonePanelMap.get(zoneName).get(1).getText());
            supplyAir.setFlow(supplyFlow);
            
            ReturnAir returnAir = zone.getReturnAir().get(0);
            returnAir.setSystem(ahsName);
            Flow returnFlow = returnAir.getFlow();
            if(zonePanelMap.get(zoneName).get(2).getText() == null || zonePanelMap.get(zoneName).get(2).getText().length() == 0){
                returnFlow.setValue(0.0);
            }
            else{
                returnFlow.setValue(Double.valueOf(zonePanelMap.get(zoneName).get(2).getText()));
            }
            returnFlow.setUnits(zonePanelMap.get(zoneName).get(3).getText());
            returnAir.setFlow(returnFlow);
            
            List<SupplyAir> supplyAirList = new ArrayList<SupplyAir>();
            supplyAirList.add(supplyAir);
            List<ReturnAir> returnAirList = new ArrayList<ReturnAir>();
            returnAirList.add(returnAir);
            
            zone.setSupplyAir(supplyAirList);
            zone.setReturnAir(returnAirList);
            
            this.airflowMissingInfo.getZones().put(zoneName, zone);     //update
        }
        
        //reset walls in order to update data from user input
        for(String wallName : this.airflowMissingInfo.getWalls().keySet()){
            Wall wall = this.airflowMissingInfo.getWalls().get(wallName);
            if(this.wallPanelMap.get(wallName).getText() == null || this.wallPanelMap.get(wallName).getText().length() == 0){
                wall.setAzimuth(0.0);
            }
            else{
                wall.setAzimuth(Double.valueOf(this.wallPanelMap.get(wallName).getText()));
            }
            this.airflowMissingInfo.getWalls().put(wallName, wall);      //update
        }
    }
    
    private void combineFinalResult(){
        Map<String,Object> map = new HashMap<String,Object>(); 
        map.put("name", airflowQueriedInfo.getName());
        map.put("description", airflowQueriedInfo.getDescription());
        
        map.put("ahs", airflowMissingInfo.getAhsList());
        map.put("levels", airflowQueriedInfo.getLevels());
        
        List<Zone> zones = new ArrayList<Zone>();
        for(String zoneName: airflowQueriedInfo.getZones().keySet()){
            Zone zone = airflowQueriedInfo.getZones().get(zoneName);
            Zone zoneMissing = airflowMissingInfo.getZones().get(zoneName);
            zone.setReturnAir(zoneMissing.getReturnAir());
            zone.setSupplyAir(zoneMissing.getSupplyAir());
            zones.add(zone);
        }
        map.put("zones", zones);
        
        List<Wall> walls = new ArrayList<Wall>();
        for(String wallName : airflowQueriedInfo.getWalls().keySet()){
            Wall wall = airflowQueriedInfo.getWalls().get(wallName);
            Wall wallMissing = airflowMissingInfo.getWalls().get(wallName);
            if(wallName.contains("Exterior")){
                wall.setAzimuth(wallMissing.getAzimuth());
            }
            walls.add(wall);
        }
        map.put("walls", walls);
        JSONObject jsonObject = JSONObject.fromObject(map);
        FileOperator fileOperator = new FileOperator();
        fileOperator.writeFile(jTextField1.getText(), this.finalFileName, jsonObject.toString());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

    private AirflowMissingInfo airflowMissingInfo;
    private AirflowQueriedInfo airflowQueriedInfo;
    private Map<String, List<javax.swing.JTextField>> zonePanelMap = new HashMap<String, List<javax.swing.JTextField>>();
    private Map<String, javax.swing.JTextField> wallPanelMap = new HashMap<String, javax.swing.JTextField>();
    private String finalFileName;

    /**
     * @return the airflowMissingInfo
     */
    public AirflowMissingInfo getAirflowMissingInfo() {
        return airflowMissingInfo;
    }

    /**
     * @param airflowMissingInfo the airflowMissingInfo to set
     */
    public void setAirflowMissingInfo(AirflowMissingInfo airflowMissingInfo) {
        this.airflowMissingInfo = airflowMissingInfo;
    }

    /**
     * @return the airflowQueriedInfo
     */
    public AirflowQueriedInfo getAirflowQueriedInfo() {
        return airflowQueriedInfo;
    }

    /**
     * @param airflowQueriedInfo the airflowQueriedInfo to set
     */
    public void setAirflowQueriedInfo(AirflowQueriedInfo airflowQueriedInfo) {
        this.airflowQueriedInfo = airflowQueriedInfo;
    }

    /**
     * @return the finalFileName
     */
    public String getFinalFileName() {
        return finalFileName;
    }

    /**
     * @param finalFileName the finalFileName to set
     */
    public void setFinalFileName(String finalFileName) {
        this.finalFileName = finalFileName;
    }

    @Action
    public void closeDialog() {
        this.dispose();
    }
    
    private int nextLabelNum = 11;
    private int nextPanelNum = 5;
    private int nextTextFieldNum = 4;
}
